#!/usr/bin/env python
# Usage: shell name_of_container
import sys
import subprocess
import json

cmd = 'docker inspect {}'.format(sys.argv[1])
output = subprocess.check_output(cmd, shell=True).decode('utf-8')
data = json.loads(output)

port = data[0]['NetworkSettings']['Ports']['22/tcp'][0]['HostPort']

cmd = 'ssh -A -p {} root@localhost'.format(port)
subprocess.call(cmd, shell=True)